### ISSUE TITLE
Unable to login to dashboard due to missing roles

### ISSUE THREAD

**Issue by ryanmboyce** [hassio-addons/addon-shinobi#12]
# Problem/Motivation

Seeing error logs in hass.io supervisor after addon successfully installed

## Expected behavior

Log in to the dashboard and work. Create a role maybe on install of addon?

## Actual behavior

Page just reloads after clicking Login

## Steps to reproduce

Try to login again

Logs attached
![image](https://user-images.githubusercontent.com/28747183/47758086-b10d1680-dc66-11e8-8669-25a5287d5518.png)

**Comment by jaclindberg** [comment]
Did you follow the steps in the documentation correctly?

https://github.com/hassio-addons/addon-shinobi/blob/v0.2.0/README.md

The installation of this add-on is pretty straightforward and not different in comparison to installing any other Hass.io add-on.

Add our Hass.io add-ons repository to your Hass.io instance.
Install the "Shinobi Pro" add-on.
Start the "Shinobi Pro" add-on
Check the logs of the "Shinobi Pro" add-on to see if everything went well.
Surf to the superuser admin panel: http://hassio.local:7440/super
Log in with the superuser credentials as specified in the add-on configuration.
Create a Shinobi user account.
Logout from the superuser panel.
You are now ready to use Shinobi, use the freshly created login from now on.

**Comment by ryanmboyce** [comment]
Yes however I cannot get to step 7 because I cannot log in...

**Comment by frenck** [comment]
This add-on has been deprecated some time ago already and has now been removed from the add-on store.

If you are looking for an alternative: https://github.com/hassio-addons/addon-motioneye

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-motioneye">hassio-addons/addon-motioneye</a></strong></div><div>motionEye - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-motioneye</div></blockquote>
