### ISSUE TITLE
Unable to start service.

### ISSUE THREAD

**Issue by arretx** [hassio-addons/addon-shinobi#2]
# Problem/Motivation

Attempting to follow the simple installation instructions.  

## Expected behavior

Expecting the service to start after installation, step 3 "Start the Shinobi Pro Add-on"

## Actual behavior

The start button spins, turns red, fades out, and nothing happens.  No log of errors on the add-on page.  Set the log level to trace...still nothing.

**Comment by arretx** [comment]
Port issue.  Apparently something else hijacked port 5000 so I set it to 5001 and it started.  I finally found the error log in the Hassio -> System tab -> System Log page where I was used to looking at the little "i" in the developer tools.

**Comment by arretx** [comment]
It would be nice to be able to change the port link on the open webui hyperlink as it seems that it's hard coded at port 5000.

**Comment by arretx** [comment]
I'm just going to leave this open.  ;).  After logging in to the interface, I simply loop back to the login.  There's no prompt to setup a shinobi account.

**Comment by jsonnet** [comment]
Just had the same problem, after some googling I found out the solution is to add /super to the url. (eg. http://hassio.local:5000/super)

**Comment by frenck** [comment]
@arretx, sorry to say, but the issue woth the link "Open web UI"  is not fixable.
This is a known limitation of Hass.io.

We are currently using 2 ports (http/https). At this time, there is no way to tell which one is used and signal Hass.io to change its behavior.
