### ISSUE TITLE
CPU usage is shown as NaN

### ISSUE THREAD

**Issue by ascillato** [hassio-addons/addon-shinobi#4]
# Problem/Motivation

> (Why the issue was filed)

The CPU usage is shown as NaN in Shinobi running in standard Hassio.

![cpu_shinobi](https://user-images.githubusercontent.com/35405447/42050608-cc391226-7adf-11e8-8605-8d7f02e9959a.jpg)

Also the memory is shown as nearly 98% but Hassio reports less than 50% at the same moment.

![cpu](https://user-images.githubusercontent.com/35405447/42050614-d0086d98-7adf-11e8-8fe5-30cd17c03d41.jpg)

## Expected behavior

> (What you expected to happen)

CPU and Memory to be displayed as Hassio reports

## Actual behavior

> (What actually happened)

CPU is NaN
Memory is double the real usage

## Steps to reproduce

> (How can someone else make/see it happen)

Install Shinobi add-on from dashboard Hassio menu

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

In the [community blog of shinobi addon for hassio](https://community.home-assistant.io/t/community-hass-io-add-on-shinobi-pro/49767?u=frenck), the user g0g0 has proposed the following change:

in the file:

https://github.com/hassio-addons/addon-shinobi/blob/master/shinobi/rootfs/etc/cont-init.d/20-init-configuration.sh#L22

change this

`CONFIG=$(hass.jq "${CONFIG}" ".cpuUsageMarker=\"cpu\"")`

to this

`CONFIG=$(hass.jq "${CONFIG}" ".cpuUsageMarker=\"CPU\"")`

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-shinobi">hassio-addons/addon-shinobi</a></strong></div><div>addon-shinobi - Shinobi Pro - Community Hass.io Add-on for Home Assistant</div></blockquote>

**Comment by ascillato** [comment]
Hi, there is something else I can help with this?

**Comment by ascillato** [comment]
Hi @frenck 

Is there something else I can help with this bug?

**Comment by ascillato** [comment]
Help

**Comment by frenck** [comment]
This add-on has been deprecated some time ago already and has now been removed from the add-on store.

If you are looking for an alternative: https://github.com/hassio-addons/addon-motioneye

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-motioneye">hassio-addons/addon-motioneye</a></strong></div><div>motionEye - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-motioneye</div></blockquote>
