### ISSUE TITLE
Videos are not deleted per "Number of Days to keep Videos" setting

### ISSUE THREAD

**Issue by e1miran** [hassio-addons/addon-shinobi#7]
## Expected behavior

> Videos should be deleted if older than "Number of Days to keep Videos".

## Actual behavior

> All videos are retained regardless of "Number of Days to keep Videos" setting.

## Steps to reproduce

> Set "Number of Days to keep Videos" to any integer.  Videos are not erased once the days have surpassed.

**Comment by ascillato** [comment]
The same issue is happening to me. I was about to open this issue also.

@frenck

Can you take a look into it? Thanks

**Comment by ascillato** [comment]
Hi,

The issue stills there. How can I help to solve this?

**Comment by frenck** [comment]
@ascillato You can't...

https://community.home-assistant.io/t/community-hass-io-add-on-shinobi-pro/49767/98?u=frenck

<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/frenck/200/13184_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-shinobi-pro/49767/98?u=frenck">Community Hass.io Add-on: Shinobi Pro</a></strong></div><div>⚠ Deprecation Announcement So here is a sad message. I’ve been working on this add-on quite some time lately. The more energy I put in to it, the more it becomes clear that this add-on has no future.  Therefore I have decided to drop this add-on in the near future and mark it deprecated immediately.  Reasoning:    The Shinobi project is not maturing. As a matter of fact, IMHO the quality of the project is degrading the last couple of months. Have you ever looked at the Shinobi source co...</div></blockquote>

**Comment by frenck** [comment]
This add-on has been deprecated some time ago already and has now been removed from the add-on store.

If you are looking for an alternative: https://github.com/hassio-addons/addon-motioneye

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-motioneye">hassio-addons/addon-motioneye</a></strong></div><div>motionEye - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-motioneye</div></blockquote>
